///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ImageDetect
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ImageDetectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("058ffc0c-62d8-4219-9154-4e915ecf7501")]
    public partial class ImageDetectRepository : RepoGenBaseFolder
    {
        static ImageDetectRepository instance = new ImageDetectRepository();
        ImageDetectRepositoryFolders.KauffmanTireAppFolder _kauffmantire;

        /// <summary>
        /// Gets the singleton class instance representing the ImageDetectRepository element repository.
        /// </summary>
        [RepositoryFolder("058ffc0c-62d8-4219-9154-4e915ecf7501")]
        public static ImageDetectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ImageDetectRepository() 
            : base("ImageDetectRepository", "/", null, 0, false, "058ffc0c-62d8-4219-9154-4e915ecf7501", ".\\RepositoryImages\\ImageDetectRepository058ffc0c.rximgres")
        {
            _kauffmantire = new ImageDetectRepositoryFolders.KauffmanTireAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("058ffc0c-62d8-4219-9154-4e915ecf7501")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The KauffmanTire folder.
        /// </summary>
        [RepositoryFolder("6d02c08c-8b3c-4e08-ab0c-bacc8e5979ed")]
        public virtual ImageDetectRepositoryFolders.KauffmanTireAppFolder KauffmanTire
        {
            get { return _kauffmantire; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class ImageDetectRepositoryFolders
    {
        /// <summary>
        /// The KauffmanTireAppFolder folder.
        /// </summary>
        [RepositoryFolder("6d02c08c-8b3c-4e08-ab0c-bacc8e5979ed")]
        public partial class KauffmanTireAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _formcontrolngpristinenguntouchedngInfo;
            RepoItemInfo _formcontrolngpristinenguntouchedng1Info;
            RepoItemInfo _formcontrolngpristinengvalidngnotInfo;
            RepoItemInfo _textInfo;

            /// <summary>
            /// Creates a new KauffmanTire  folder.
            /// </summary>
            public KauffmanTireAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KauffmanTire", "/dom[@domain='www.kauffmantire.com']", parentFolder, 30000, null, false, "6d02c08c-8b3c-4e08-ab0c-bacc8e5979ed", "")
            {
                _formcontrolngpristinenguntouchedngInfo = new RepoItemInfo(this, "FormControlNgPristineNgUntouchedNg", "?/?/section/div[1]/tag[2]/div/div/div/div[1]/div/div[2]/div[1]/div[2]/div[1]/select", 30000, null, "be60d842-9dc9-48bd-a508-61415a6cabe3");
                _formcontrolngpristinenguntouchedng1Info = new RepoItemInfo(this, "FormControlNgPristineNgUntouchedNg1", "?/?/section/div[1]/tag[2]/div/div/div/div[1]/div/div[2]/div[1]/div[2]/div[2]/select", 30000, null, "52aff12f-97ae-40f4-addd-7f9b726629f9");
                _formcontrolngpristinengvalidngnotInfo = new RepoItemInfo(this, "FormControlNgPristineNgValidNgNot", "?/?/section/div[1]/tag[2]/div/div/div/div[1]/div/div[2]/div[1]/div[2]/div[3]/select", 30000, null, "957be918-3cf8-49eb-95c6-2ac565dd8b60");
                _textInfo = new RepoItemInfo(this, "Text", "?/?/section/div[1]/tag[2]/div/div/div/div[1]/div/div[2]/div[1]/div[2]/div[4]/input[@type='text']", 30000, null, "d6dcb7dc-f9d4-4463-bfcd-123868ffacf7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6d02c08c-8b3c-4e08-ab0c-bacc8e5979ed")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6d02c08c-8b3c-4e08-ab0c-bacc8e5979ed")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FormControlNgPristineNgUntouchedNg item.
            /// </summary>
            [RepositoryItem("be60d842-9dc9-48bd-a508-61415a6cabe3")]
            public virtual Ranorex.SelectTag FormControlNgPristineNgUntouchedNg
            {
                get
                {
                    return _formcontrolngpristinenguntouchedngInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FormControlNgPristineNgUntouchedNg item info.
            /// </summary>
            [RepositoryItemInfo("be60d842-9dc9-48bd-a508-61415a6cabe3")]
            public virtual RepoItemInfo FormControlNgPristineNgUntouchedNgInfo
            {
                get
                {
                    return _formcontrolngpristinenguntouchedngInfo;
                }
            }

            /// <summary>
            /// The FormControlNgPristineNgUntouchedNg1 item.
            /// </summary>
            [RepositoryItem("52aff12f-97ae-40f4-addd-7f9b726629f9")]
            public virtual Ranorex.SelectTag FormControlNgPristineNgUntouchedNg1
            {
                get
                {
                    return _formcontrolngpristinenguntouchedng1Info.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FormControlNgPristineNgUntouchedNg1 item info.
            /// </summary>
            [RepositoryItemInfo("52aff12f-97ae-40f4-addd-7f9b726629f9")]
            public virtual RepoItemInfo FormControlNgPristineNgUntouchedNg1Info
            {
                get
                {
                    return _formcontrolngpristinenguntouchedng1Info;
                }
            }

            /// <summary>
            /// The FormControlNgPristineNgValidNgNot item.
            /// </summary>
            [RepositoryItem("957be918-3cf8-49eb-95c6-2ac565dd8b60")]
            public virtual Ranorex.SelectTag FormControlNgPristineNgValidNgNot
            {
                get
                {
                    return _formcontrolngpristinengvalidngnotInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FormControlNgPristineNgValidNgNot item info.
            /// </summary>
            [RepositoryItemInfo("957be918-3cf8-49eb-95c6-2ac565dd8b60")]
            public virtual RepoItemInfo FormControlNgPristineNgValidNgNotInfo
            {
                get
                {
                    return _formcontrolngpristinengvalidngnotInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("d6dcb7dc-f9d4-4463-bfcd-123868ffacf7")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("d6dcb7dc-f9d4-4463-bfcd-123868ffacf7")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}